import { ProductsType } from "@/types/ProductsTypes";

const freshCertifications = ["Export Grade", "Quality Selected", "Cold-Chain Ready"];
const frozenCertifications = ["IQF / Frozen", "Export Grade", "No Preservatives"];
const freshStorage = "Keep refrigerated in clean, ventilated conditions according to the product requirements.";
const frozenStorage = "Keep frozen at -18 C. Do not refreeze after thawing.";

type ProductInput = Omit<ProductsType, "origin" | "uses" | "certifications" | "storage" | "highlights"> & {
  uses?: string[];
  storage?: string;
  certifications?: string[];
  highlights?: string[];
};

const product = (item: ProductInput): ProductsType => ({
  origin: "Egypt",
  uses: ["Wholesale supply", "Retail packs", "Foodservice", "Export programs"],
  storage: item.category === "frozen" ? frozenStorage : freshStorage,
  certifications: item.category === "frozen" ? frozenCertifications : freshCertifications,
  highlights: ["Reliable supply", "Flexible packaging", "Export ready", "Careful handling"],
  ...item,
});

export const products: ProductsType[] = [
  product({
    slug: "fresh-carrots",
    name: "Fresh Carrots",
    category: "fresh",
    type: "vegetable",
    tagline: "Bright, clean, and naturally sweet Egyptian carrots",
    shortDescription: "Export-ready carrots selected for color, crunch, and shelf life.",
    description: "Fresh Egyptian carrots graded for consistent size, natural sweetness, and strong shelf life for wholesale, retail packs, foodservice, and export shipments.",
    uses: ["Retail fresh packs", "Fresh salads", "Juices and smoothies", "Foodservice preparation"],
    highlights: ["Bright color", "Crisp bite", "Bulk ready", "Premium grade"],
    color: "#E67E22",
    accentColor: "#D35400",
  }),
  product({
    slug: "fresh-potatoes",
    name: "Fresh Potatoes",
    category: "fresh",
    type: "vegetable",
    tagline: "Reliable Egyptian potatoes for bulk and retail supply",
    shortDescription: "Firm potatoes prepared for dependable export and wholesale use.",
    description: "Fresh potatoes sourced from trusted Egyptian growers and selected for firmness, clean skin, and reliable performance across retail, processing, and foodservice channels.",
    storage: "Store in a cool, dry, dark, and ventilated place. Avoid direct sunlight.",
    highlights: ["Firm texture", "Bulk supply", "Consistent quality", "Export ready"],
    color: "#B8863B",
    accentColor: "#D6A85C",
  }),
  product({
    slug: "colored-peppers",
    name: "Colored Bell Peppers",
    category: "fresh",
    type: "vegetable",
    tagline: "Red, yellow, and green peppers with vibrant market appeal",
    shortDescription: "Glossy colored peppers selected for crunch, sweetness, and strong visual quality.",
    description: "Fresh colored bell peppers harvested at optimal maturity and handled carefully to preserve shine, firmness, and natural sweetness for importers, supermarkets, and foodservice buyers.",
    uses: ["Retail displays", "Fresh salads", "Grilling and roasting", "Prepared vegetable mixes"],
    highlights: ["Vibrant colors", "Crisp walls", "Premium grade", "Retail ready"],
    color: "#C0392B",
    accentColor: "#F2C14E",
  }),
  product({
    slug: "fresh-broccoli",
    name: "Fresh Broccoli",
    category: "fresh",
    type: "vegetable",
    tagline: "Fresh green crowns prepared for professional supply",
    shortDescription: "Carefully selected broccoli with firm heads and fresh color.",
    description: "Fresh broccoli prepared for export buyers who need reliable appearance, clean handling, and consistent freshness across shipments.",
    highlights: ["Fresh green color", "Firm crowns", "Quality selected", "Cold-chain ready"],
    color: "#2E7D32",
    accentColor: "#66BB6A",
  }),
  product({
    slug: "citrus-fruits",
    name: "Citrus Fruits",
    category: "fresh",
    type: "fruit",
    tagline: "Egyptian oranges, mandarins, and lemons for seasonal export",
    shortDescription: "Seasonal citrus selected for juice, aroma, and bright presentation.",
    description: "Egyptian citrus fruits including oranges, mandarins, and lemons supplied according to season, size, packing, and importer requirements.",
    uses: ["Retail fruit packs", "Juice programs", "Wholesale markets", "Food trading"],
    highlights: ["Seasonal supply", "Bright appearance", "Flexible packing", "Export handling"],
    color: "#F39C12",
    accentColor: "#F5B041",
  }),
  product({
    slug: "fresh-garlic",
    name: "Fresh Garlic",
    category: "fresh",
    type: "vegetable",
    tagline: "Clean, aromatic garlic selected for trading and distribution",
    shortDescription: "Egyptian garlic prepared for bulk buyers and food trading companies.",
    description: "Fresh garlic selected for aroma, dryness, and market quality, with packaging options suitable for wholesale, distribution, and export programs.",
    storage: "Store in a dry, cool, and well-ventilated area away from moisture.",
    color: "#7D8B73",
    accentColor: "#D9D2BF",
  }),
  product({
    slug: "fresh-onions",
    name: "Fresh Onions",
    category: "fresh",
    type: "vegetable",
    tagline: "Dependable Egyptian onions for wholesale and export",
    shortDescription: "Firm onions selected for dry skin, size, and reliable storage.",
    description: "Fresh Egyptian onions prepared for importers and distributors, with attention to firmness, dry outer skin, grading, and export handling.",
    storage: "Store in a cool, dry, and ventilated place. Keep away from moisture.",
    color: "#B5651D",
    accentColor: "#D18B47",
  }),
  product({
    slug: "fresh-green-beans",
    name: "Fresh Green Beans",
    category: "fresh",
    type: "vegetable",
    tagline: "Tender fresh beans with clean color and crisp texture",
    shortDescription: "Fresh green beans prepared for premium retail and foodservice supply.",
    description: "Fresh green beans selected for tenderness, color, and consistency, suitable for supermarkets, wholesalers, and foodservice buyers.",
    color: "#168246",
    accentColor: "#55A56F",
  }),
  product({
    slug: "frozen-strawberries",
    name: "Frozen Strawberries",
    category: "frozen",
    type: "fruit",
    tagline: "Frozen Egyptian strawberries with vivid color and natural sweetness",
    shortDescription: "Frozen strawberries prepared for year-round industrial and retail use.",
    description: "Egyptian strawberries frozen to preserve flavor, color, and texture for smoothies, desserts, bakeries, jams, and food manufacturing.",
    uses: ["Smoothies", "Bakeries", "Jams and sauces", "Frozen fruit packs"],
    highlights: ["Year-round supply", "Natural sweetness", "Frozen ready", "No additives"],
    color: "#C0392B",
    accentColor: "#E91E63",
  }),
  product({
    slug: "frozen-mango",
    name: "Frozen Mango",
    category: "frozen",
    type: "fruit",
    tagline: "Sweet mango pieces frozen for consistent supply",
    shortDescription: "Frozen mango prepared for juices, desserts, and food manufacturing.",
    description: "Frozen mango pieces supplied for buyers who need dependable tropical flavor, attractive color, and convenient year-round availability.",
    uses: ["Juices", "Smoothies", "Desserts", "Food manufacturing"],
    color: "#F4A62A",
    accentColor: "#FFC857",
  }),
  product({
    slug: "frozen-green-peas",
    name: "Frozen Green Peas",
    category: "frozen",
    type: "vegetable",
    tagline: "Tender green peas frozen for daily production needs",
    shortDescription: "Frozen peas selected for color, sweetness, and convenience.",
    description: "Frozen green peas prepared for retail packs, foodservice, and industrial buyers requiring consistent color, taste, and portion control.",
    uses: ["Retail packs", "Ready meals", "Foodservice", "Mixed vegetables"],
    color: "#43A047",
    accentColor: "#81C784",
  }),
  product({
    slug: "frozen-green-beans",
    name: "Frozen Green Beans",
    category: "frozen",
    type: "vegetable",
    tagline: "Frozen beans cut and prepared for convenient cooking",
    shortDescription: "Frozen green beans for retail, foodservice, and processing buyers.",
    description: "Frozen green beans processed for convenience while preserving color, tenderness, and clean presentation for professional buyers.",
    color: "#0F7A4A",
    accentColor: "#4CAF50",
  }),
  product({
    slug: "frozen-molokhia",
    name: "Frozen Molokhia",
    category: "frozen",
    type: "vegetable",
    tagline: "Authentic Egyptian molokhia frozen for consistent quality",
    shortDescription: "Frozen molokhia prepared for traditional cooking and distribution.",
    description: "Frozen Egyptian molokhia supplied for importers and food trading companies looking for authentic taste, convenient storage, and steady availability.",
    color: "#1B5E20",
    accentColor: "#388E3C",
  }),
  product({
    slug: "frozen-okra-zero",
    name: "Frozen Okra Zero",
    category: "frozen",
    type: "vegetable",
    tagline: "Small-size okra frozen for premium traditional dishes",
    shortDescription: "Premium small okra selected for uniform size and clean appearance.",
    description: "Frozen okra zero selected for small size, tenderness, and premium presentation, suitable for retail packs and foodservice buyers.",
    color: "#2E7D32",
    accentColor: "#66BB6A",
  }),
  product({
    slug: "frozen-okra-medium",
    name: "Frozen Okra Medium",
    category: "frozen",
    type: "vegetable",
    tagline: "Medium-size okra for reliable frozen supply",
    shortDescription: "Frozen medium okra prepared for flexible cooking and distribution.",
    description: "Frozen medium okra supplied for buyers who need steady sizing, dependable quality, and export-ready packaging options.",
    color: "#388E3C",
    accentColor: "#7CB342",
  }),
  product({
    slug: "frozen-okra-whole",
    name: "Frozen Okra Whole",
    category: "frozen",
    type: "vegetable",
    tagline: "Whole okra frozen to preserve shape and freshness",
    shortDescription: "Whole frozen okra with natural green color and convenient storage.",
    description: "Whole frozen okra prepared to preserve shape, color, and cooking performance for importers, retailers, and foodservice buyers.",
    color: "#33691E",
    accentColor: "#8BC34A",
  }),
  product({
    slug: "mixed-vegetables",
    name: "Mixed Vegetables",
    category: "frozen",
    type: "vegetable",
    tagline: "Convenient frozen vegetable mix for retail and foodservice",
    shortDescription: "A practical frozen mix prepared for quick cooking and consistent supply.",
    description: "Frozen mixed vegetables prepared for buyers who need convenience, consistency, and flexible packaging for retail or professional kitchens.",
    color: "#2F9E44",
    accentColor: "#F4A62A",
  }),
  product({
    slug: "frozen-carrot-cuts",
    name: "Frozen Carrot Cuts",
    category: "frozen",
    type: "vegetable",
    tagline: "Ready-to-use carrot cuts for frozen programs",
    shortDescription: "Frozen carrot cuts with bright color and convenient preparation.",
    description: "Frozen carrot cuts prepared for retail packs, foodservice, and mixed vegetable programs with clean color and dependable sizing.",
    color: "#E67E22",
    accentColor: "#F39C12",
  }),
  product({
    slug: "frozen-baba-ghanoush",
    name: "Frozen Baba Ghanoush",
    category: "frozen",
    type: "vegetable",
    tagline: "Frozen Egyptian-style baba ghanoush for convenient serving",
    shortDescription: "A prepared frozen eggplant product for foodservice and retail buyers.",
    description: "Frozen baba ghanoush prepared for buyers seeking convenient Egyptian-style products suitable for foodservice, retail, and distribution.",
    storage: "Keep frozen at -18 C. Follow thawing instructions before serving.",
    color: "#6D4C41",
    accentColor: "#A1887F",
  }),
  product({
    slug: "frozen-spinach",
    name: "Frozen Spinach",
    category: "frozen",
    type: "vegetable",
    tagline: "Frozen spinach with deep green color and practical preparation",
    shortDescription: "Frozen spinach prepared for cooking, processing, and retail packs.",
    description: "Frozen spinach supplied for importers and foodservice buyers requiring clean color, convenient storage, and consistent cooking performance.",
    color: "#1B5E20",
    accentColor: "#43A047",
  }),
  product({
    slug: "frozen-broccoli",
    name: "Frozen Broccoli",
    category: "frozen",
    type: "vegetable",
    tagline: "Frozen broccoli florets for year-round supply",
    shortDescription: "Frozen broccoli prepared for retail, foodservice, and ready-meal buyers.",
    description: "Frozen broccoli supplied for buyers who need convenient preparation, stable storage, and reliable year-round availability.",
    color: "#2E7D32",
    accentColor: "#66BB6A",
  }),
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}

export function getProductsByCategory(category: ProductsType["category"]) {
  return products.filter((product) => product.category === category);
}

export function getProductSegment(product: ProductsType) {
  return `${product.category}-${product.type}` as const;
}
