import { ProductsType } from "@/types/ProductsTypes";

export const products: ProductsType[] = [
  {
    slug: "red-bell",
    name: "Red Bell Peppers",
    category: "fresh",
    type: "vegetable",
    origin: "Egypt",
    tagline: "Vibrant, sweet, and naturally rich in Vitamin C",
    shortDescription: "Glossy red peppers with crisp walls and a sweet finish.",
    description:
      "Hand-picked red bell peppers harvested at optimal ripeness for vivid color, crisp texture, and natural sweetness. Every batch is handled through Al Baraka's quality-control process for freshness and consistency.",
    uses: [
      "Fresh salads and crudites",
      "Roasted vegetable mixes",
      "Stuffed peppers",
      "Soups, stews, and stir-fries",
    ],
    storage: "Keep refrigerated at 4-8 C. Use within 7-10 days of delivery.",
    certifications: ["ISO Certified", "HACCP Certified", "100% Natural"],
    highlights: ["Farm fresh", "Sweet profile", "No preservatives", "Premium grade"],
    color: "#C0392B",
    accentColor: "#E74C3C",
  },
  {
    slug: "green-bell",
    name: "Green Bell Peppers",
    category: "fresh",
    type: "vegetable",
    origin: "Egypt",
    tagline: "Crisp, robust, and packed with fresh flavor",
    shortDescription: "Firm green peppers with satisfying crunch and clean aroma.",
    description:
      "Farm-fresh green bell peppers with thick walls, deep color, and a savory bite. Ideal for wholesale kitchens, fresh packs, and prepared foods that need reliable quality.",
    uses: [
      "Fresh salads and crudites",
      "Fajitas and sauteed mixes",
      "Stuffed peppers",
      "Grilled vegetable platters",
    ],
    storage: "Keep refrigerated at 4-8 C. Use within 7-10 days of delivery.",
    certifications: ["ISO Certified", "HACCP Certified", "100% Natural"],
    highlights: ["Firm texture", "Rich flavor", "Cold-chain handled", "Premium grade"],
    color: "#1F7A45",
    accentColor: "#2E9E62",
  },
  {
    slug: "yellow-bell",
    name: "Yellow Bell Peppers",
    category: "fresh",
    type: "vegetable",
    origin: "Egypt",
    tagline: "Sun-ripened golden sweetness",
    shortDescription: "Bright yellow peppers with gentle sweetness and color.",
    description:
      "Golden yellow bell peppers selected for their balanced sweetness, glossy skins, and strong visual appeal. A premium choice for colorful fresh displays and foodservice prep.",
    uses: [
      "Fresh salads and crudites",
      "Colorful stir-fries",
      "Roasted vegetables",
      "Stuffed peppers and casseroles",
    ],
    storage: "Keep refrigerated at 4-8 C. Use within 7-10 days of delivery.",
    certifications: ["ISO Certified", "HACCP Certified", "100% Natural"],
    highlights: ["Sun-ripened", "Bright color", "Naturally sweet", "Premium grade"],
    color: "#D99A21",
    accentColor: "#F2C14E",
  },
  {
    slug: "carrots",
    name: "Fresh Carrots",
    category: "fresh",
    type: "vegetable",
    origin: "Egypt",
    tagline: "Farm-fresh sweetness, harvested at peak ripeness",
    shortDescription: "Clean, bright carrots selected for crunch and sweetness.",
    description:
      "Fresh carrots grown for natural sweetness, vibrant color, and reliable shelf life. Each lot is carefully graded and prepared for retail, foodservice, and bulk supply.",
    uses: [
      "Fresh salads and crudites",
      "Soups, stews, and stir-fries",
      "Fresh juices and smoothies",
      "Roasted vegetable sides",
    ],
    storage: "Keep refrigerated at 0-4 C. Use within 2-3 weeks of delivery.",
    certifications: ["ISO Certified", "HACCP Certified", "Premium Grade"],
    highlights: ["Natural sweetness", "Crisp bite", "Cold-chain handled", "Bulk ready"],
    color: "#E67E22",
    accentColor: "#D35400",
  },
  {
    slug: "apples",
    name: "Polish Apples",
    category: "fresh",
    type: "fruit",
    origin: "Poland",
    tagline: "Europe's finest orchards, delivered with traceability",
    shortDescription: "Hand-picked apples from Poland's premium orchards.",
    description:
      "Premium Polish apples sourced through our sister company Marianna in Warsaw. Crisp, juicy, and carefully handled to preserve orchard quality from Europe to the Middle East.",
    uses: [
      "Fresh snacking and fruit bowls",
      "Baking, tarts, and pastries",
      "Applesauce and desserts",
      "Retail fresh packs",
    ],
    storage: "Keep refrigerated at 0-4 C. Best consumed within 4-6 weeks.",
    certifications: ["ISO Certified", "HACCP Certified", "Grade 1"],
    highlights: ["Polish origin", "Crisp texture", "Traceable supply", "Premium grade"],
    color: "#B83232",
    accentColor: "#E45A4F",
  },
  {
    slug: "strawberries",
    name: "Frozen Strawberries",
    category: "frozen",
    type: "fruit",
    origin: "Egypt",
    tagline: "Flash-frozen at peak ripeness, nutrients locked in",
    shortDescription: "IQF strawberries with vivid color and natural sweetness.",
    description:
      "Hand-picked strawberries immediately flash-frozen using IQF technology to lock in flavor, color, and nutrition. No preservatives, no additives, and ready for year-round use.",
    uses: [
      "Smoothies and bowls",
      "Baking and pastries",
      "Jams and sauces",
      "Frozen fruit packs",
    ],
    storage: "Keep frozen at -18 C. Do not refreeze after thawing.",
    certifications: ["ISO Certified", "HACCP Certified", "IQF Technology", "No Preservatives"],
    highlights: ["IQF frozen", "No additives", "Year-round supply", "Premium grade"],
    color: "#C0392B",
    accentColor: "#E91E63",
  },
];

export function getProductBySlug(slug: string) {
  return products.find((product) => product.slug === slug);
}
